#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {[0] = LAYOUT_planck_1x2uC(LT(3, KC_TAB), KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC, LCTL_T(KC_ESC), KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_ENT, KC_MPLY, KC_LALT, KC_LGUI, LSFT_T(KC_ENT), LCTL_T(KC_ESC), LT(1, KC_SPC), LT(3, KC_BSPC), KC_LEFT, KC_DOWN, KC_UP, KC_RGHT),
                                                              [1] = LAYOUT_planck_1x2uC(KC_GRV, KC_GRV, KC_HOME, KC_PGUP, KC_PGDN, KC_END, KC_MINS, KC_EQL, KC_QUOT, KC_LBRC, KC_RBRC, KC_DEL, KC_TILD, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_QUOT, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_BSLS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, MO(2), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
                                                              [2] = LAYOUT_planck_1x2uC(RGB_M_SN, RGB_M_SW, RGB_M_B, RGB_M_P, RGB_M_R, RGB_M_K, RGB_M_X, RGB_M_G, RGB_M_T, KC_NO, KC_NO, QK_BOOT, KC_NO, KC_NO, KC_NO, RGB_SPD, RGB_SPI, RGB_RMOD, RGB_MOD, RGB_TOG, BL_TOGG, BL_STEP, BL_BRTG, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_HUI, RGB_HUD, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_SPC, KC_TRNS, RGB_SAD, RGB_VAD, RGB_VAI, RGB_SAI),
                                                              [3] = LAYOUT_planck_1x2uC(KC_GRV, KC_GRV, KC_NO, KC_EQL, KC_GT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_QUOT, KC_NO, KC_NO, KC_VOLD, KC_VOLU, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_DEL, KC_TAB, KC_MPLY, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO)};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
